#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
     path: /{_locale}
     controller: App\Controller\UserController::login
     defaults:
          _locale: 'en'
     requirements:
          _locale: 'en|fr|de'
          
login:
    path: /{_locale}/login
    controller: App\Controller\UserController::login
    defaults:
      _locale: 'en'   
    requirements:
       _locale: 'en|fr|de' 
 
logout:
    path: /logout
    
      
register_user:
     path: /{_locale}/register/user
     controller: App\Controller\UserController::registerUser    
     requirements:
          _locale: 'en|fr|de' 
          
search_patient_list:
     path: /{_locale}/search/patient
     controller: App\Controller\SearchController::searchPatientList
     defaults:
          _locale: 'en'
     requirements:
          _locale: 'en|fr|de'          

username_available:
    path: /username/available
    controller: App\Controller\UserController::usernameAvailable
    methods: ['POST']                 