#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
     path: /{_locale}
     defaults:
        _controller: FrameworkBundle:Redirect:Redirect
        route: search_patient_list
        permanent: true
        _locale: 'en'  
     requirements:
        _locale: 'en|fr|de'   
        
admin_user:
     path: /{_locale}/admin/user
     defaults:
        _controller: App\Controller\AdminController:adminUser
        _locale: 'en'  
     requirements:
        _locale: 'en|fr|de'           
          
login:
    path: /{_locale}/login
    controller: App\Controller\UserController::login
    defaults:
      _locale: 'en'   
    requirements:
       _locale: 'en|fr|de' 
 
logout:
    path: /logout
           
search_patient_list:
     path: /{_locale}/search/patient
     controller: App\Controller\SearchController::searchPatientList
     defaults:
          _locale: 'en'
     requirements:
          _locale: 'en|fr|de'          


username_available:
    path: /username/available
    controller: App\Controller\UserController::usernameAvailable
    methods: ['POST']
               
drugs_list:
     path: /{_locale}/drugs/list
     controller: App\Controller\DrugsController::drugsList
     defaults:
          _locale: 'en'
     requirements:
          _locale: 'en|fr|de'  
                     
addressbook_list:
     path: /{_locale}/addressbook/list
     controller: App\Controller\AddressbookController::addressbookList
     defaults:
          _locale: 'en'
     requirements:
          _locale: 'en|fr|de'  

addressbook_detail:
     path: /{_locale}/addressbook/detail/{doctor}
     controller: App\Controller\AddressbookController::addressbookDetail
     defaults:
          _locale: 'en'
     requirements:
          _locale: 'en|fr|de'
          doctor: '^[0-9]+$'

addressbook_add:
     path: /{_locale}/addressbook/add
     controller: App\Controller\AddressbookController::addDoctor
     defaults:
          _locale: 'en'
     requirements:
          _locale: 'en|fr|de'
                  
admin_main:
     path: /{_locale}/admin/main
     controller: App\Controller\AdminController::adminMain
     defaults:
          _locale: 'en'
     requirements:
          _locale: 'en|fr|de'
                     
patient_record:
     path: /{_locale}/patient/record
     controller: App\Controller\PatientController::patientRecord
     defaults:
          _locale: 'en'
     requirements:
          _locale: 'en|fr|de'   
