#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
     path: /{_locale}
     controller: App\Controller\UserController::userLogin
     defaults:
          _locale: 'en'
     requirements:
          _locale: 'en|fr|de'