#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
     path: /{_locale}
     controller: App\Controller\UserController::userLogin
     defaults:
          _locale: 'en'
     requirements:
          _locale: 'en|fr|de'
          
login:
    path: /{_locale}/login
    controller: App\Controller\UserController::login
    defaults:
      _locale: 'en'   
    requirements:
      _locale: 'en|fr|de' 
 
logout:
    path: /logout
    
patient:
    path: /{_locale}/patient
    controller: App\Controller\PatientController::patientRecord
    defaults:
          _locale: 'en'
    requirements:
          _locale: 'en|fr|de'