CREATE DATABASE mldemo;
CREATE TABLE table_drugs (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255),
	supplier VARCHAR(255),
	dosage VARCHAR(255),
	contraindications VARCHAR(255),
	sideeffects VARCHAR(255),
	incompatibilities VARCHAR(255),
	overdose VARCHAR(255),
    components VARCHAR(255)
    )ENGINE = INNODB CHARACTER SET utf8 COLLATE utf8_bin;

INSERT INTO table_drugs (`name`, `supplier`, `dosage`, `contraindications`, `sideeffects`, `incompatibilities`, `overdose`, `components` ) VALUE ('Zyloprim', 'Reddy Laboratories', 'Initial dose: 100 mg orally once a day', 'Allopurinol SHOULD BE DISCONTINUED AT THE FIRST APPEARANCE OF SKIN RASH OR OTHER SIGNS WHICH MAY INDICATE AN ALLERGIC REACTION.', 'acute gout attack', 'none', 'Massive overdosing or acute poisoning by Allopurinol has not been reported.', 'Allopurinol is known chemically as 1,5-dihydro-4H-pyrazolo [3,4-d ]pyrimidin-4-one.');
INSERT INTO table_drugs (`name`, `supplier`, `dosage`, `contraindications`, `sideeffects`, `incompatibilities`, `overdose`, `components` ) VALUE ('Botox', 'Allergan plc', 'The potency Units of BOTOX (onabotulinumtoxinA) for injection are specific to the preparation and assay method utilized. ', 'Botox is contraindicated in patients who are hypersensitive to any botulinum toxin preparation or to any of the components in the formulation.', 'Common side effects of Botox include: antibody development.', 'All the companies recommend that different.', 'Excessive doses of Botox (onabotulinumtoxinA) for injection may be expected to produce neuromuscular weakness with a variety of symptoms.', 'Botox (onabotulinumtoxinA) for injection is a sterile, vacuum-dried purified botulinum toxin type A, produced from fermentation of Hall strain Clostridium botulinum type A, and intended for intramuscular, intradetrusor and intradermal use.');
INSERT INTO table_drugs (`name`, `supplier`, `dosage`, `contraindications`, `sideeffects`, `incompatibilities`, `overdose`, `components` ) VALUE ('Clindamycin', 'Akorn, Inc.', 'Applies to the following strengths: 150 mg; 150 mg/mL.', 'Clindamycin hydrochloride capsules are contraindicated in individuals with a history of hypersensitivity to preparations containing clindamycin or lincomycin.', 'Along with its needed effects, clindamycin may cause some unwanted effects.', 'The product information should be consulted; compatibility and duration of stability of drug mixtures varies according to concentration and other conditions.', 'Significant mortality was observed in mice at an intravenous dose of 855 mg/kg and in rats at an oral or subcutaneous dose of approximately 2618 mg/kg. In the mice, convulsions and depression were observed.', 'Clindamycin hydrochloride is the hydrated hydrochloride salt of clindamycin.');
INSERT INTO table_drugs (`name`, `supplier`, `dosage`, `contraindications`, `sideeffects`, `incompatibilities`, `overdose`, `components` ) VALUE ('Diflucan', 'Pfizer Inc.', 'The recommended dosage of DIFLUCAN for candidiasis is 150 mg as a single oral dose.', 'Diflucan (fluconazole) is contraindicated in patients who have shown hypersensitivity to fluconazole or to any of its excipients.', 'Along with its needed effects, fluconazole (the active ingredient contained in Diflucan) may cause some unwanted effects. ', 'Some azoles, including fluconazole, have been associated with prolongation of the QT interval on the electrocardiogram.', 'There have been reports of overdose with fluconazole accompanied by hallucination and paranoid behavior.', 'Diflucan® (fluconazole), the first of a new subclass of synthetic triazole antifungal agents, is available as tablets for oral administration, as a powder for oral suspension.');
INSERT INTO table_drugs (`name`, `supplier`, `dosage`, `contraindications`, `sideeffects`, `incompatibilities`, `overdose`, `components` ) VALUE ('Erythromycin', 'Amneal Pharmaceuticals LLC', 'Mild to moderate infection: 250 to 500 mg (base, estolate, stearate) or 400 to 800 mg (ethylsuccinate) orally every 6 hours.', 'Erythromycin is contraindicated in patients with known hypersensitivity to this antibiotic.', 'Along with its needed effects, erythromycin may cause some unwanted effects. ', 'There have been reports of hepatic dysfunction, including increased liver enzymes, and hepatocellular and/or cholestatic hepatitis, with or without jaundice, occurring in patients receiving oral erythromycin products.', 'In case of overdosage, erythromycin should be discontinued. ', 'Erythromycin Tablets, USP are an antibacterial product containing erythromycin, USP, in a unique, nonenteric film coating for oral administration.');
INSERT INTO table_drugs (`name`, `supplier`, `dosage`, `contraindications`, `sideeffects`, `incompatibilities`, `overdose`, `components` ) VALUE ('Fioricet', 'Allergan plc', 'One or 2 tablets every 4 hours as needed. Total daily dosage should not exceed 6 tablets.', 'Butalbital is habit-forming and potentially abusable. Consequently, the extended use of Fioricet is not recommended.', 'Some side effects of acetaminophen / butalbital / caffeine may occur that usually do not need medical attention.', 'The most frequently reported adverse reactions are drowsiness, lightheadedness, dizziness, sedation, shortness of breath, nausea, vomiting, abdominal pain, and intoxicated feeling.', 'Following an acute overdosage of butalbital, acetaminophen, and caffeine, toxicity may result from the barbiturate or the acetaminophen.', 'Butalbital (5-allyl-5-isobutylbarbituric acid) is a short- to intermediate-acting barbiturate. ');
INSERT INTO table_drugs (`name`, `supplier`, `dosage`, `contraindications`, `sideeffects`, `incompatibilities`, `overdose`, `components` ) VALUE ('Glucophage', 'Bristol-Myers Squibb Company', 'There is no fixed dosage regimen for the management of hyperglycemia in patients with type 2 diabetes with GLUCOPHAGE or GLUCOPHAGE XR or any other pharmacologic agent.', 'Glucophage and Glucophage XR are contraindicated in patients with:1.Severe renal impairment (eGFR below 30 mL/min/1.73 m2).', 'Common side effects of Glucophage include: lactic acidosis, diarrhea, nausea, and vomiting. ', 'none', 'Overdose of metformin hydrochloride has occurred, including ingestion of amounts greater than 50 grams.', 'Metformin hydrochloride is a white to off-white crystalline compound with a molecular formula of C4H11N5 • HCl and a molecular weight of 165.63.');
INSERT INTO table_drugs (`name`, `supplier`, `dosage`, `contraindications`, `sideeffects`, `incompatibilities`, `overdose`, `components` ) VALUE ('Hydroxyzine', 'Global Pharmaceuticals', 'Applies to the following strengths: hydrochloride 25 mg/mL.', 'Hydroxyzine, when administered to the pregnant mouse, rat, and rabbit, induced fetal abnormalities in the rat and mouse at doses substantially above the human therapeutic range. ', 'Along with its needed effects, hydroxyzine may cause some unwanted effects.', 'THE POTENTIATING ACTION OF Hydroxyzine MUST BE CONSIDERED WHEN THE DRUG IS USED IN CONJUNCTION WITH CENTRAL NERVOUS SYSTEM DEPRESSANTS SUCH AS NARCOTICS, NON-NARCOTIC ANALGESICS AND BARBITURATES.', 'The most common manifestation of overdosage of Hydroxyzine pamoate is hypersedation.', 'Hydroxyzine pamoate, USP is designated chemically as 1-(p-chlorobenzhydryl) 4-[2-(2-hydroxyethoxy) ethyl] diethylenediamine salt of 1,1′-methylene bis (2 hydroxy-3-naphthalene carboxylic acid).');
INSERT INTO table_drugs (`name`, `supplier`, `dosage`, `contraindications`, `sideeffects`, `incompatibilities`, `overdose`, `components` ) VALUE ('Ibuprofen', 'Akorn, Inc.', 'Applies to the following strengths: 100 mg/5 mL.', 'Ibuprofen tablets are contraindicated in patients with known hypersensitivity to Ibuprofen.', 'Commonly reported side effects of ibuprofen include: hemorrhage, vomiting, anemia, decreased hemoglobin, eosinophilia, and hypertension.', 'Ibuprofen tablets cannot be expected to substitute for corticosteroids or to treat corticosteroid insufficiency.', 'Approximately 1½ hours after the reported ingestion of from 7 to10 Ibuprofen tablets (400 mg), a 19-month old child weighing 12 kg was seen in the hospital emergency room, apneic and cyanotic, responding only to painful stimuli.', 'Ibuprofen tablets contain the active ingredient Ibuprofen.');
INSERT INTO table_drugs (`name`, `supplier`, `dosage`, `contraindications`, `sideeffects`, `incompatibilities`, `overdose`, `components` ) VALUE ('Juluca', 'ViiV Healthcare', 'The recommended dosage of JULUCA is one tablet taken orally once daily with a meal.', 'Juluca is contraindicated in patients: with previous hypersensitivity reaction to dolutegravir or rilpivirine.', 'Along with its needed effects, dolutegravir/rilpivirine may cause some unwanted effects.', 'Hypersensitivity reactions have been reported with dolutegravir and were characterized by rash, constitutional findings, and sometimes organ dysfunction, including liver injury.', 'There is no known specific treatment for overdose with Juluca.', 'Juluca is a fixed-dose combination tablet containing dolutegravir (as dolutegravir sodium), an INSTI, and rilpivirine (as rilpivirine hydrochloride), an NNRTI.');
